name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server:  ftp.flickertraffic.com
          username: ftpadria@flickertraffic.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 1257
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            .cpanel.yml
